# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Lap_trinh_tool_python\Src_tool_video_ai13052026\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(950, 831)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Lap_trinh_tool_python\\Src_tool_video_ai13052026\\logo_256x256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Widget.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Widget)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_input = QtWidgets.QLabel(self.centralwidget)
        self.lb_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.lb_input.setFont(font)
        self.lb_input.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lb_input.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_input.setObjectName("lb_input")
        self.horizontalLayout_7.addWidget(self.lb_input)
        self.lb_result = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        self.lb_result.setFont(font)
        self.lb_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_result.setObjectName("lb_result")
        self.horizontalLayout_7.addWidget(self.lb_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txt_input_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_input_3.setMinimumSize(QtCore.QSize(260, 280))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.txt_input_3.setFont(font)
        self.txt_input_3.setObjectName("txt_input_3")
        self.horizontalLayout_6.addWidget(self.txt_input_3)
        self.txt_result = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_result.setMinimumSize(QtCore.QSize(360, 280))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.txt_result.setFont(font)
        self.txt_result.setReadOnly(True)
        self.txt_result.setObjectName("txt_result")
        self.horizontalLayout_6.addWidget(self.txt_result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txt_log = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_log.setMinimumSize(QtCore.QSize(0, 260))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.txt_log.setFont(font)
        self.txt_log.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.txt_log.setReadOnly(True)
        self.txt_log.setObjectName("txt_log")
        self.horizontalLayout_5.addWidget(self.txt_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        Widget.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Widget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menubar.setObjectName("menubar")
        Widget.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Widget)
        self.statusbar.setObjectName("statusbar")
        Widget.setStatusBar(self.statusbar)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Tool Check balance Maycs"))
        self.lineEdit_2.setStyleSheet(_translate("Widget", "background-color: #cccccc;\n"
"color: black;\n"
""))
        self.lineEdit_2.setText(_translate("Widget", "Key_CapTra ->>>"))
        self.lineEdit_4.setStyleSheet(_translate("Widget", "background-color: #cccccc;\n"
"color: black;\n"
""))
        self.lineEdit_3.setStyleSheet(_translate("Widget", "background-color: #999999;\n"
"color: black;\n"
""))
        self.lineEdit_3.setText(_translate("Widget", "Đường dẫn file proxy ->>>"))
        self.lineEdit.setStyleSheet(_translate("Widget", "background-color: #999999;\n"
"color: black;\n"
""))
        self.lb_input.setText(_translate("Widget", "Nhập Thẻ Cần Check:"))
        self.lb_result.setText(_translate("Widget", "Kết Quả"))
        self.pushButton_2.setStyleSheet(_translate("Widget", "QPushButton {\n"
"    background-color: #1e90ff;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #187bcd;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #145ea8;\n"
"}\n"
""))
        self.pushButton_2.setText(_translate("Widget", "Check Balance"))
        self.pushButton.setStyleSheet(_translate("Widget", "QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"}\n"
""))
        self.pushButton.setText(_translate("Widget", "Mở lịch sử file check"))
        self.txt_log.setStyleSheet(_translate("Widget", "QTextEdit {\n"
"    color: lime;\n"
"    background-color: black;\n"
"    font-family: Consolas;\n"
"    font-size: 10pt;\n"
"}\n"
""))
        self.txt_log.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XEM TIẾN TRÌNH, THÔNG BÁO TẠI ĐÂY !</p></body></html>"))
